
-- jdbc/stcom0014 jdbc:oracle:thin:@TLADBXD5.dktetrix.net:1530:tetrix02 stcom

Insert into PARAMETRES_DETAIL (TTI_NUM_TYPE_TIERS_TIR,TIR_NUM_TIERS_TIR,TIR_SOUS_NUM_TIERS_TIR,PAR_CODE_APPLICATION,PAR_CODE_PARAMETRE,PAR_VALEUR_PARAMETRE_ALPHA,PAR_VALEUR_PARAMETRE_NUM,PAR_COMMENTAIRES,PAR_DATE_UPD,PAR_USER_UPD,PAR_DATE_CRT,PAR_USER_CRT) values ('7','2','2','ActivationBatch','TraitementBatchSandBox','Y',null,'ActivationBatch',to_date('30/10/13','DD/MM/RR'),'Z13JOFFR',to_date('30/10/13','DD/MM/RR'),'Z13JOFFR');


-- data for the batch
insert into STCOM.TTRANSACTION_CAISSE_CA 
(TTI_NUM_TYPE_TIERS, TIR_NUM_TIERS, TIR_SOUS_NUM_TIERS, TCA_DATE_HEURE_TRANS, TCA_NUM_HOTESSE, TCA_NUM_CAISSE, TCA_NUM_TRANSACTION, TCA_NUM_LIGNE_TRANSACTION, TCA_DATE_ECRITURE, TCA_MODE_SAISIE, TCA_MOTIF_COMMERCIAL_KS, TCA_MOTIF_COMMERCIAL, TCA_CODE_ARTICLE, TCA_QUANTITE, TCA_MONTANT_KS, TCA_MONTANT, TCA_DEVISE_MONTANT, TCA_CODE_TVA, TCA_TAUX_TVA, TCA_TYPE_TRANSACTION, TCA_ZONE_LIBRE, TCA_PROMO, NMV_CODE_NATURE_MOUVEMENT, TCA_TOP_TMT_CPT_INFO, TCA_TOP_TMT_DECOMPTE, TCA_TOP_TMT_CA, TCA_TOP_TMT_CLIENT, TCA_TOP_TMT_STOCK, TCA_TOP_TMT_TICKET_CLIENT, TCA_TOP_TMT_TROCATHLON, TCA_TOP_TMT_ATELIER, TCA_MONTANT_HT_KS, TCA_MONTANT_HT, TCA_TOP_BIPAGE, TCA_TOP_TMT_LAD, TCA_MONTANT_INIT, TCA_MONTANT_INIT_KS, TCA_TOP_TMT_STAT, TCA_ZONE_LIBRE_2, TCA_TOP_TMT_ERESA) 
values 
(7, 2, 2, 30-OCT-13 09.00.18.000000 AM, '0047', '0001', 8429, 2, 31-OCT-13 05.20.13.000000 PM, 'N', 1, NULL, '93211', 1, 300, NULL, NULL, 1, NULL, '1', '0               0', '0', NULL, 0, -999, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2', NULL, NULL, NULL, NULL, NULL, NULL);